services:
  bot-swap:
    build: .
    container_name: bot-swap
    env_file:
      - .env
    restart: always
    environment:
      - ONNX_PROVIDER=CUDAExecutionProvider
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
