services:
  bot-swap:
    build: .
    container_name: bot-swap
    env_file:
      - .env
    restart: always
    environment:
      - ONNX_PROVIDER=CPUExecutionProvider
    depends_on:
      - redis
    networks:
      - bot-network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - bot-network

volumes:
  redis_data:
    driver: local

networks:
  bot-network:
    driver: bridge
